print(r"     /~\ ")
print("    ( oo|")
print("    _\=/_")
print("   /  _  \ ")
print(r"  //|/.\|\\")
print(" ||  \ /  ||")
print("============")
print("|          |")
print("|          |")
print("|          |")